const MembrosData = [
  {
    id: "0",
    name: "Safira",
    birthDate: "21/11/1984",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
    lot: {
      cep: "00000-00",
      state: "São Paulo",
      city: "Agudos",
      settlement: "MN1191111 - CA NOME ASSENTAMENTO",
      incra_allotment_number: "13",
      access_way: "Rua de terra",
      coordinates: { lat: -22.500326, lng: -48.9864157 },
    },
    production: {
      operational_core: "CODEAGRO",
      limit: "Sim",
      marking: "Sim",
      legalized: "Sim",
    },
  },
  {
    id: "1",
    name: "José",
    birthDate: "01/01/1990",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Pescador/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
    lot: {
      cep: "00000-00",
      state: "São Paulo",
      city: "Agudos",
      settlement: "MN1191111 - CA NOME ASSENTAMENTO",
      incra_allotment_number: "13",
      access_way: "Rua de terra",
      coordinates: { lat: -22.500326, lng: -48.9864157 },
    },
  },
  {
    id: "2",
    name: "Agusto",
    birthDate: "10/04/1963",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Do Lar",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
    lot: {
      cep: "00000-00",
      state: "São Paulo",
      city: "Agudos",
      settlement: "MN1191111 - CA NOME ASSENTAMENTO",
      incra_allotment_number: "13",
      access_way: "Rua de terra",
      coordinates: { lat: -22.500326, lng: -48.9864157 },
    },
  },
  {
    id: "3",
    name: "Carmem",
    birthDate: "13/08/1971",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Inativo/a",
    lot: {
      cep: "00000-00",
      state: "São Paulo",
      city: "Agudos",
      settlement: "MN1191111 - CA NOME ASSENTAMENTO",
      incra_allotment_number: "13",
      access_way: "Rua de terra",
      coordinates: { lat: -22.500326, lng: -48.9864157 },
    },

  },
];

export default MembrosData;
