const MembrosData = [
  {
    id: 0,
    name: "Safira",
    birthDate: "21/11/1984",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
  },
  {
    id: 1,
    name: "José",
    birthDate: "01/01/1990",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Pescador/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
  },
  {
    id: 2,
    name: "Agusto",
    birthDate: "10/04/1963",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Do Lar",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Ativo/a",
  },
  {
    id: 3,
    name: "Carmem",
    birthDate: "13/08/1971",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "Bauru - São Paulo",
    incra: "Sim",
    coleta: "2911",
    address: "H287+Q7 Agudos, São Paulo",
    status: "Inativo/a",
  },
];

export default MembrosData;