import AC0132000_PDS_POLO_PIRA_DE_RAv3_2008mb_1 from "../../../assets/doc/AC0132000_PDS_POLO_PIRA_DE_RA v3_2008mb-1.png";
import AC0132000_PDS_POLO_PIRA_DE_RAv3_2018mb_1 from "../../../assets/doc/AC0132000_PDS_POLO_PIRA_DE_RA v3_2018mb-1.png";
import GO0136000_PA_SANTA_MARTA_v3_2008mb_1 from "../../../assets/doc/GO0136000_PA_SANTA_MARTA_v3_2008mb-1.png";
import GO0136000_PA_SANTA_MARTA_v3_2018mb_1 from "../../../assets/doc/GO0136000_PA_SANTA_MARTA_v3_2018mb-1.png";

const MembrosData = [
  {
    id: "0",
    name: "Lislei Antônio Viana Santos",
    phone: "(11) 99999-9999",
    email: "email@conafer.org.br",
    birthDate: "21/11/1984",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "brasileira",
    naturality: "Três de Maio - Rio Grande do Sul",
    incra: "Sim",
    status_rb: "Assentado",
    collect_code: "754",
    address: "Ramal Bom Jesus, 2504",
    is_active: true,
    settlement_code: "AC013200000041",
    lot: {
      operational_core: "Não possui",
      cep: "00000-00",
      state: "Acre",
      city: "Senador Guiomard",
      settlement: "AC0132000 - PDS POLO PIRÃ DE RÃ",
      incra_allotment_number: "99",
      access_way: "Direto por estrada/rua de terra",
      coordinates: { lat: -10.139881, lng: -67.691507 },
      lot_geometry: {
        before: AC0132000_PDS_POLO_PIRA_DE_RAv3_2008mb_1,
        after: AC0132000_PDS_POLO_PIRA_DE_RAv3_2018mb_1,
      },
    },
    houses: [
      {
        house: 1,
        residents: 2,
        rooms: 5,
        builder: "Tijolo/alvenaria com revestimento/reboco",
        internalLining: "Sim",
        floor: "Cerâmica/piso frio",
        environmentalRisk: "Não",
        roofCover: "Telha de amianto",
      },
    ],
    residents: [
      {
        allotment: "",
        resident_name: "Lislei Antônio Viana Santos",
        kinship: "Reponsável pelo lote	",
        sex: "Masculino",
        birthdate: "22/12/1962",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Agricultor (a)/Do Lar",
        generates_income: true,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Grupo religioso",
        demotivating_activity: "",
        retired: false,
        work_outside:
          "	Agricultura - No plantio, capina, roçado e/ou colheita de produtos de lavoura, horta ou pomar destinados à comercialização",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "Problemas de coluna",
        type_treatment: "Alopatia, Homeopatia",
        access_treatment: "Hospital público, Posto de saúde",
      },
      {
        resident_name: "Valdirene dos Santos",
        allotment: "",
        kinship: "Cônjuge",
        sex: "Feminino",
        birthdate: "12/02/1970",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Não Possui",
        generates_income: false,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Grupo religioso",
        demotivating_activity: "",
        retired: false,
        work_outside: "",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "Depressão",
        type_treatment: "Alopatia, Homeopatia",
        access_treatment: "Hospital público, Posto de saúde",
      },
    ],
    familyUnitIdentification: {
      settlement_code: "Lislei Antônio Viana Santos",
      status: "Beneficiário",
      cpf: "000.000.000-00",
      rg: "00000000",
      nis: "",
      marital_status: "Casado(a)",
      mother_name: "Valquíria Viana Santos",
      spouse_name: "Valdirene dos Santos",
      spouse_cpf: "000.000.000-00",
      citizenship: "Três de Maio - RS",
      nationality: "Brasileira",
    },
    production: {
      operational_core: "CODEAGRO",
      limit: "Sim",
      marking: "Sim",
      legalized: "Sim",
    },
  },
  {
    id: "1",
    name: "Cauã Marcos Miguel Assunção",
    phone: "(11) 99999-9999",
    email: "email@conafer.org.br",
    birthDate: "24/05/1965",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "brasileira",
    naturality: "Sanclerlândia",
    incra: "Sim",
    status_rb: "Assentado",
    collect_code: "754",
    address: "Rua mato grosso Quadra 13, lote 1",
    is_active: true,
    settlement_code: "GO0136000",
    lot: {
      operational_core: "",
      cep: "00000-00",
      state: "Goiás",
      city: "Sanclerlândia",
      settlement: "GO0136000 - PA SANTA MARTA",
      incra_allotment_number: "424",
      access_way: "Direto por estrada/rua de terra",
      coordinates: { lat: -13.900583, lng: -50.158089 },
      lot_geometry: {
        before: GO0136000_PA_SANTA_MARTA_v3_2008mb_1,
        after: GO0136000_PA_SANTA_MARTA_v3_2018mb_1,
      },
    },
    houses: [
      {
        house: 1,
        residents: 2,
        rooms: 5,
        builder: "Tijolo/alvenaria com revestimento/reboco",
        internalLining: "Sim",
        floor: "Cerâmica/piso frio",
        environmentalRisk: "Não",
        roofCover: "Telha de amianto",
      },
    ],
    residents: [
      {
        allotment: "",
        resident_name: "Cauã Marcos Miguel Assunção",
        kinship: "Reponsável pelo lote",
        sex: "Masculino",
        birthdate: "22/12/1962",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Agricultor (a)/Do Lar",
        generates_income: true,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Grupo religioso",
        demotivating_activity: "",
        retired: false,
        work_outside:
          "Agricultura - No plantio, capina, roçado e/ou colheita de produtos de lavoura, horta ou pomar destinados à comercialização",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "",
        type_treatment: "",
        access_treatment: "",
      },
      {
        allotment: "",
        resident_name: "DIvines Ferreira de Assunção",
        kinship: "Cônjuge",
        sex: "Feminino",
        birthdate: "12/02/1970",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Não Possui",
        generates_income: false,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Grupo religioso",
        demotivating_activity: "",
        retired: false,
        work_outside: "",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "Depressão",
        type_treatment: "Alopatia, Homeopatia",
        access_treatment: "Hospital público, Posto de saúde",
      },
    ],
    familyUnitIdentification: {
      settlement_code: "Cauã Marcos Miguel Assunção",
      status: "Beneficiário",
      cpf: "000.000.000-00",
      rg: "00000000",
      nis: "",
      marital_status: "Casado(a)",
      mother_name: "Francisca da Silva",
      spouse_name: "Ivines Ferreira de Assunção",
      spouse_cpf: "000.000.000-00",
      citizenship: "Sanclerlândia - GO",
      nationality: "Brasileira",
    },
    production: {
      operational_core: "CODEAGRO",
      limit: "Sim",
      marking: "Sim",
      legalized: "Sim",
    },
  },
  {
    id: "2",
    name: "Alberto dos Santos",
    phone: "(11) 99999-9999",
    email: "email@conafer.org.br",
    birthDate: "24/05/1965",
    school: "Ens. Fund. Completo",
    sourceOfIncome: "Agricultor/a",
    cpf: "000.000.000-00",
    nationality: "Brasileira",
    naturality: "Espirito Santo - Espírito Santo",
    incra: "Sim",
    status_rb: "Assentado",
    collect_code: "754",
    address: "Rua mato grosso Quadra 13, lote 1",
    is_active: true,
    settlement_code: "RJ002900000103",
    lot: {
      operational_core: "",
      cep: "00000-00",
      state: "Rio de Janeiro",
      city: "Silva Jardim",
      settlement: "RJ0029000 - PA CAMBUCAES",
      incra_allotment_number: "16",
      access_way: "Direto por estrada/rua de terra",
      coordinates: { lat: -22.601016, lng: -42.375417 },
      lot_geometry: {
        before: GO0136000_PA_SANTA_MARTA_v3_2008mb_1,
        after: GO0136000_PA_SANTA_MARTA_v3_2018mb_1,
      },
    },
    houses: [
      {
        house: 1,
        residents: 2,
        rooms: 5,
        builder: "Tijolo/alvenaria com revestimento/reboco",
        internalLining: "Sim",
        floor: "Cerâmica/piso frio",
        environmentalRisk: "Não",
        roofCover: "Telha de amianto",
      },
    ],
    residents: [
      {
        allotment: "",
        resident_name: "Alberto dos Santos",
        kinship: "Reponsável pelo lote",
        sex: "Masculino",
        birthdate: "22/12/1962",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Agricultor(a)",
        generates_income: true,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Nenhuma",
        demotivating_activity: "Falta de tempo",
        retired: false,
        work_outside:
          "Agricultura - No plantio, capina, roçado e/ou colheita de produtos de lavoura, horta ou pomar destinados à comercialização",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "",
        type_treatment: "",
        access_treatment: "",
      },
      {
        allotment: "",
        resident_name: "Gabriela dos Santos",
        kinship: "Cônjuge",
        sex: "Feminino",
        birthdate: "12/02/1970",
        schooling: "Ens. Fund. Incompleto",
        main_source_income: "Não Possui",
        generates_income: false,
        batch_work_time: 0,
        issues_invoice: false,
        ex_beneficiary: false,
        activity: "Nenhuma",
        demotivating_activity: "",
        retired: false,
        work_outside: "",
        initial_age_work_outside: "",
        deficiency: false,
        last_diceases: "",
        type_treatment: "",
        access_treatment: "",
      },
    ],
    familyUnitIdentification: {
      settlement_code: "Alberto dos Santos",
      status: "Beneficiário",
      cpf: "000.000.000-00",
      rg: "00000000",
      nis: "",
      marital_status: "Casado(a)",
      mother_name: "Maria da Silva",
      spouse_name: "Gabriela dos Santos",
      spouse_cpf: "000.000.000-00",
      citizenship: "Espirito Santo - ES",
      nationality: "Brasileira",
    },
    production: {
      operational_core: "CODEAGRO",
      limit: "Sim",
      marking: "Sim",
      legalized: "Sim",
    },
  },
];

export default MembrosData;
